### 服务器配置
server:
  port: 8084
### spring配置
spring:
  ## 数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/qipai?useSSL=false&characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: root

  ## jpa配置
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate.format_sql: false
    open-in-view: true


## redis配置
  redis:
    ##默认redis客户端连接为0 可修改port: 6379
    database: 0
    host: localhost
    port: 6379
    jedis:
      pool:
        max-idle: 8
        max-active: 8
        max-wait: -1ms
      timeout: 5000
